name: gbpn_messages
description: GBPN Messages

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_native_splash: ^2.1.2+1
  flutter_bloc: ^8.0.1
  dio: ^4.0.4
  http: ^0.13.4
  shared_preferences: ^2.0.13
  simple_animations: ^4.0.1
  fluttertoast: ^8.0.9
  pusher_channels_flutter: ^1.0.5
  flutter_local_notifications: ^9.4.0
  event_bus: ^2.0.0
  intl: ^0.17.0
  flutter_dtmf: ^2.0.2
  flutter_masked_text2: ^0.9.1
  url_launcher: ^6.0.20
  image_picker: ^0.8.5
  file_picker: ^4.5.1
  audioplayers: ^0.20.1
  video_player: ^2.3.0
  sticky_headers: ^0.2.0
  cached_network_image: ^3.2.0
  pull_to_refresh: ^2.0.0
  shimmer: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/